name: Ruby

on:
  schedule:
    - cron: "42 */6 * * *"
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  readme:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Generate readme
      env:
       TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
       TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
       TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
       TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
       WHOOP_KEY: ${{ secrets.WHOOP_KEY }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       HCTI_API_USER_ID: ${{ secrets.HCTI_API_USER_ID }}
       HCTI_API_KEY: ${{ secrets.HCTI_API_KEY }}
      run: bundle exec ruby generate.rb

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Mike Coutermarsh
        author_email: coutermarsh.mike+robot@gmail.com
        message: "Auto updating my readme!"
        add: "*.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
